### ISSUE TITLE
Getting blank page

### ISSUE THREAD

**Issue by phaoost** [cobbler/cobbler-web#117]
Hello. I am getting a blank page.
Here is what I get from telnet:

```
$ telnet 127.0.0.1 4200
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET / HTTP/1.1
Host: 127.0.0.1
Connection: close

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Accept-Ranges: bytes
Content-Length: 1283
ETag: W/"503-Zf1+jMqOzjnqRDOvItB+qXoZhl8"
Date: Thu, 21 Jul 2022 20:19:35 GMT
Connection: close

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Cobbler</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Cobbler helps you manage your installations.">
  <meta name="theme-color" content="#317EFB"/>
  <link rel="shortcut icon" href="#">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&amp;display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Raleway&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css"></head>
<body class="mat-typography">

<app-root></app-root>

<script src="runtime.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="styles.js" defer></script><script src="vendor.js" type="module"></script><script src="main.js" type="module"></script></body>

<!-- image assets attributions:
    Photo by fauxels from Pexels (group around the table)
    Photo by Pixabay from Pexels (Gears and Cogs)
    Photo by ready made from Pexels (mobile phone displaying recycle symbol)
    -->
</html>

```

**Comment by SchoolGuy** [comment]
Thank you for opening this issue! To be able to help you better first of all it would be great what you are trying to achieve. This repo describes the next version of Cobbler Web. However this is still in development and thus it is expected that many things are not yet working.

What you are showing is the landing page of our Angular App and thus I don't see any problem here. You need to use a browser (telnet really won't work). Please extend the issue description with the information required so we can try to help you.

**Comment by mcd1992** [comment]
Same issue in chromium `103.0.5060.134` and firefox `102.0.1`. Not familiar with angular but it looks like the `<app-root></app-root>` element isn't being targeted and instead its looking for `cobbler-root`?

![image](https://user-images.githubusercontent.com/434626/180664505-420b5799-2759-4531-a679-71472e32342f.png)

This environment is following the dev setup as documented in: https://cobbler.github.io/cobbler-web/additional-documentation/development-setup.html

cobbler commit `07717b9703c7c0ce452af258e79fb0c66136d699`
cobbler-web commit `588be223785e60d4a4c697b6a95cddc0ca8d89e8`

EDIT:
Yea looks like just editing `projects/cobbler-frontend/src/index.html` to be `<cobbler-root>` fixes the issue. Most recent commits talk about changing selector prefix from app to cobbler.

**Comment by SchoolGuy** [comment]
@mcd1992 Oh indeed that is correctly debugged. I will fix it with a PR. Gimme a sec. It seems that the locally compiled version does not hit that weirdly.
