### ISSUE TITLE
Remove `app.module.ts`

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler-web#265]
**Is your feature request related to a problem? Please describe.**
As a developer I don't want to have dead code in the repository.

**Describe the solution you'd like**
Remove the app module without the application breaking. This shouldn't be the case since we transitioned to Angular 17 but it should be ensured.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Subhraaa** [comment]
why would you remove app.module.ts? please elaborate

**Comment by SchoolGuy** [comment]
@Subhraaa Because with Angular 17+ standalone components were added to Angular and if the whole project is ported to them then it is not needed anymore. Since this project was ported to Angular Standalone the file remained in the repository but it is now time to remove it.

**Comment by moudgalya1223** [comment]
hello @SchoolGuy  please assign this to me created a pr as well
