### ISSUE TITLE
unsubscribe in all views

### ISSUE THREAD

**Issue by 00Kadie00** [cobbler/cobbler-web#286]
**Is your feature request related to a problem? Please describe.**
This will provide a clean code, less memory leaks and will avoid unexpectet behavior. 

**Describe the solution you'd like**
Use angular lifecycle hook OnDestroy, create a new subscription and add every code block with subscribe in the subscription. Afterwards unsubscribe the subscription in the lifecycle hook. Repeat for every view which uses subscribe.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SchoolGuy** [comment]
Interesting read: https://stackoverflow.com/a/41177163/4730773

**Comment by SchoolGuy** [comment]
Since Angular v16 there is a developer preview feature that further improves the code. As it is only preview I don't want to use it for now.

- Angular Docs: https://angular.dev/api/core/rxjs-interop/takeUntilDestroyed
- Blog article with example: https://angularindepth.com/posts/1518
