### ISSUE TITLE
Implement page for `cobbler check`

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler-web#63]
**Is your feature request related to a problem? Please describe.**

At the moment the results of `cobbler check` are not visible on the frontend. This should be fixed.

**Describe the solution you'd like**

The user should see the output of `cobbler check`.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by SchoolGuy** [comment]
@chris1984 this issue should be rather easy. The endpoint is already implemented in `cobbler-api` and as such only the UI part has to be done.

**Comment by chris1984** [comment]
@SchoolGuy ok thanks, will start to look at this one
