### ISSUE TITLE
Add custom cobbler prefix to components

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler-web#91]
**Is your feature request related to a problem? Please describe.**

Currently we use the default `app-` prefix for components. Let's use a custom prefix that suits our project more.

**Describe the solution you'd like**

Use the custom `cobbler-` prefix for all components as it shows that the components is belonging to the Cobbler project.

**Describe alternatives you've considered**

None

**Additional context**

See https://blogkashif.medium.com/change-prefix-of-component-in-angular-application-34c8d8a86dbf how to do it.

**Comment by jsowers13** [comment]
Hey there, can I work on this?

**Comment by SchoolGuy** [comment]
@jsowers13 Sure. Just fork the repo, create a branch for it and follow the blog post I linked in the issue description!

**Comment by jsowers13** [comment]
Finished. Opened Pull Request #97!
